# Generated by Django 3.2 on 2022-04-15 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='highscore',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
