# Generated by Django 3.2 on 2022-04-15 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='untisPassword',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='untisUsername',
        ),
    ]
